### ISSUE TITLE
FYI: 404ing project links in pypi

### ISSUE THREAD

**Issue by obswork** [kayvane1/brave-api#21]
Hello 👋🏾 Just stumbled on your package in pypi. Kudos for getting one up so quickly! Just wanted to give you a heads up that the Homepage and Repository project links are pointing at https://github.com/kayvane1/brave-search rather than https://github.com/kayvane1/brave-api, so they currently 404. Might be worth renaming the Github project to `brave-search` or updating the links in the pyproject.toml [file](https://github.com/kayvane1/brave-api/blob/staging/pyproject.toml#L7-L8).

**Comment by kayvane1** [comment]
Thanks for letting me know @obswork ! I'm away without a laptop this week but will fix when I get back 🙏🏼

Let me know if you find any other issues or any functionality that could be added/improved.
