### ISSUE TITLE
Valid search result_filter values are unsupported 

### ISSUE THREAD

**Issue by obswork** [kayvane1/brave-api#22]
Currently, only "web" and "query" return a valid response when passed into `result_filter` as arguments to the `search` function. The other valid filters (discussions, faq, infobox, news, videos) instead return a `ValidationError`. 

To reproduce:

```python
brave = Brave()
brave.search(q="Brave Search API", result_filter="news")
```

**Comment by kayvane1** [comment]
Thank you for raising this and sorry for the delay - solved in #34
