### ISSUE TITLE
Fields missing in NewsResult response object

### ISSUE THREAD

**Issue by obswork** [kayvane1/brave-api#23]
See title. There are a handful of fields that are defined for the `NewsResult` response object (see [docs](https://api.search.brave.com/app/documentation/news-search/responses#NewsResult)), that are currently missing in the responses returned by this package. 

To confirm:
```python
brave = Brave()
results = brave.search(q='Boeing')
dict(results.news.results[0]).keys()  # returns: ['meta_url', 'source', 'breaking', 'thumbnail', 'age']
```

**Comment by kayvane1** [comment]
Thanks for raising this, addressed in #34
