### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dmabry** [kayvane1/brave-api#29]
I find this project, very, very useful, but I noticed that there isn't a license associated with this project.  Do you intend to make this licensed either MIT, Apache2 or something else?

**Comment by kayvane1** [comment]
Glad to hear you're finding it useful! I'll raise a PR next week to add a license, it will be Apache 2.0 so it can be freely used for any use case 🚀

**Comment by dmabry** [comment]
Sounds good!  I look forward to more collaboration in the future.
