### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by harishankar-gopalan** [kayvane1/brave-api#32]
Hi team, is anyone already working on python 3.9 compatibility. While performing web search I find this specific line where type declaration is done is creating an issue.
```python
# brave/types/web/search_result.py:82
product_cluster: Optional[List[Product|Review]]
```

if I change this line to
```python
product_cluster: Optional[List[Union[Product,Review]]]
```
and importing `Union` from typing makes it compatible to Python 3.9 atleast for the web search api call.

**Comment by kayvane1** [comment]
Thanks for identifying this @harishankar-gopalan! Could you please raise a PR to make this change?

**Comment by harishankar-gopalan** [comment]
https://github.com/kayvane1/brave-api/pull/33

Here you go. Request to review and merge @kayvane1

**Comment by kayvane1** [comment]
Awesome thank you!
